services:
  _defaults:
    autoconfigure: true
    autowire: true

  Guave\SentryBundle\Twig\TwigTemplateExtension:
    tags:
      - { name: twig.extension }

  Guave\SentryBundle\Helper\TemplateHelper:
    public: false
    tags:
      - { name: twig.runtime }
