services:
  _defaults:
    autoconfigure: true
    autowire: true

  Guave\SentryBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection}

  Guave\SentryBundle\Twig\:
    resource: ../src/Twig
    tags:
      - { name: twig.extension }

  Guave\SentryBundle\Helper\TemplateHelper:
    tags:
      - { name: twig.runtime }
